### PR TITLE
Hide selection when nothing selected and hide resize cursor

### LINKED ISSUE #54: Resize handles are incorrectly shown even when nothing it selected
If nothing is selected you can the drag handles appearing in the top-left corner:

image

If you hover the mouse of the 0,0 point you'll also get a resize cursor.

The drag handles should not be rendered and the cursor shouldn't be modified if `selection.size === 0`.

### PR DESCRIPTION
**Pull request by Mxchaeltrxn**
Fixes #54

### CODE REVIEW

File: src/Editor.js [hunk 1]
```diff
@@ -257,6 +257,9 @@ const Editor = () => {
   const selectionBounds = getLayerBounds(
     doc.layers.filter(layer => selection.has(layer.id))
   );
+  const selectionBoundsFormRect =
+    selectionBounds.x1 === selectionBounds.y1 &&
+    selectionBounds.x2 === selectionBounds.y2;
```
Comment (haydn) [inline src/Editor.js]: @Mxchaeltrxn I'm not sure if it's worthwhile checking this. It currently doesn't handle the case where `x1 === x2 && y1 === y2 && x1 !== y1 && x2 !== y2`, but it's also probably easier to check `state.selection.size > 0` (as you've done for deciding to show the selection rectangles).

Comment (Mxchaeltrxn) [reply src/Editor.js]: Agreed. I just added these changes

**Comment by haydn** [comment]
@Mxchaeltrxn Looks good to me! Thanks.
